// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountAuthClient is the client API for AccountAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountAuthClient interface {
	// 注册接口
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*User, error)
	// 登录接口
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// 通过Token验证用户身份
	Check(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*User, error)
	// 更新用户资料
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*User, error)
	// 特权：通过用户ID获取用户资料
	DevGetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type accountAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountAuthClient(cc grpc.ClientConnInterface) AccountAuthClient {
	return &accountAuthClient{cc}
}

func (c *accountAuthClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAuthClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAuthClient) Check(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAuthClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAuthClient) DevGetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/DevGetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAuthServer is the server API for AccountAuth service.
// All implementations must embed UnimplementedAccountAuthServer
// for forward compatibility
type AccountAuthServer interface {
	// 注册接口
	Signup(context.Context, *SignupRequest) (*User, error)
	// 登录接口
	Signin(context.Context, *SigninRequest) (*TokenResponse, error)
	// 通过Token验证用户身份
	Check(context.Context, *TokenRequest) (*User, error)
	// 更新用户资料
	Update(context.Context, *UpdateRequest) (*User, error)
	// 特权：通过用户ID获取用户资料
	DevGetUser(context.Context, *GetUserRequest) (*User, error)
	mustEmbedUnimplementedAccountAuthServer()
}

// UnimplementedAccountAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAccountAuthServer struct {
}

func (UnimplementedAccountAuthServer) Signup(context.Context, *SignupRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedAccountAuthServer) Signin(context.Context, *SigninRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (UnimplementedAccountAuthServer) Check(context.Context, *TokenRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAccountAuthServer) Update(context.Context, *UpdateRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAccountAuthServer) DevGetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DevGetUser not implemented")
}
func (UnimplementedAccountAuthServer) mustEmbedUnimplementedAccountAuthServer() {}

// UnsafeAccountAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountAuthServer will
// result in compilation errors.
type UnsafeAccountAuthServer interface {
	mustEmbedUnimplementedAccountAuthServer()
}

func RegisterAccountAuthServer(s grpc.ServiceRegistrar, srv AccountAuthServer) {
	s.RegisterService(&AccountAuth_ServiceDesc, srv)
}

func _AccountAuth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAuth_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAuth_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).Check(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAuth_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAuth_DevGetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).DevGetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/DevGetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).DevGetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountAuth_ServiceDesc is the grpc.ServiceDesc for AccountAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AccountAuth",
	HandlerType: (*AccountAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _AccountAuth_Signup_Handler,
		},
		{
			MethodName: "Signin",
			Handler:    _AccountAuth_Signin_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _AccountAuth_Check_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountAuth_Update_Handler,
		},
		{
			MethodName: "DevGetUser",
			Handler:    _AccountAuth_DevGetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
