// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package atuh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountAuthClient is the client API for AccountAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountAuthClient interface {
	// 注册接口
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*User, error)
}

type accountAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountAuthClient(cc grpc.ClientConnInterface) AccountAuthClient {
	return &accountAuthClient{cc}
}

func (c *accountAuthClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.AccountAuth/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAuthServer is the server API for AccountAuth service.
// All implementations must embed UnimplementedAccountAuthServer
// for forward compatibility
type AccountAuthServer interface {
	// 注册接口
	Signup(context.Context, *SignupRequest) (*User, error)
	mustEmbedUnimplementedAccountAuthServer()
}

// UnimplementedAccountAuthServer must be embedded to have forward compatible implementations.
type UnimplementedAccountAuthServer struct {
}

func (UnimplementedAccountAuthServer) Signup(context.Context, *SignupRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedAccountAuthServer) mustEmbedUnimplementedAccountAuthServer() {}

// UnsafeAccountAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountAuthServer will
// result in compilation errors.
type UnsafeAccountAuthServer interface {
	mustEmbedUnimplementedAccountAuthServer()
}

func RegisterAccountAuthServer(s grpc.ServiceRegistrar, srv AccountAuthServer) {
	s.RegisterService(&AccountAuth_ServiceDesc, srv)
}

func _AccountAuth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AccountAuth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAuthServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountAuth_ServiceDesc is the grpc.ServiceDesc for AccountAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AccountAuth",
	HandlerType: (*AccountAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _AccountAuth_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
